// <auto-generated />
namespace BellumGens.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserSearchVisibility : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserSearchVisibility));
        
        string IMigrationMetadata.Id
        {
            get { return "201903190851591_UserSearchVisibility"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
