// <auto-generated />
namespace BellumGens.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TournamentActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TournamentActive));
        
        string IMigrationMetadata.Id
        {
            get { return "202006170744459_TournamentActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
