// <auto-generated />
namespace BellumGens.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SC2Groups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SC2Groups));
        
        string IMigrationMetadata.Id
        {
            get { return "202001080924098_SC2Groups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
