// <auto-generated />
namespace BellumGens.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MapPool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MapPool));
        
        string IMigrationMetadata.Id
        {
            get { return "201808241322264_Map-Pool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
