// <auto-generated />
namespace BellumGens.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ESEA_Discord : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ESEA_Discord));
        
        string IMigrationMetadata.Id
        {
            get { return "201902070820340_ESEA_Discord"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
